### PR TITLE
deSEC: Implements support for long / multistring txt records

### LINKED ISSUE #996: Long / MultiString TXT records fail with deSEC
deSEC provider doesn't allow TXT records with multiple strings, but the service splits long records automatically.

After #947 validation changes, dnscontrol fails validation for long TXT records with `ERROR: txt target >255 bytes and AUTOSPLIT not set`. Adding AUTOSPLIT to deSEC records (or splitting manually) causes dnscontrol to fail with `ERROR: TXT records with multiple strings not supported by desec`

Before, long TXT records worked, though the automatically split record caused unnecessary modifications.

### PR DESCRIPTION
**Pull request by D3luxee**
This PR will resolve #996 and #1177 the multi/long txt part is working but i suggest to wait with the merge until @tmkis2 confirmed that its working with over 500 domains since i do not have that many domains to test it.

### CODE REVIEW

File: providers/desec/desecProvider.go [hunk 1]
```diff
@@ -23,13 +24,12 @@ Info required in `creds.json`:
...
 	c.creds.token = m["auth-token"]
+	c.domainIndex = map[string]uint32{}
 	if c.creds.token == "" {
 		return nil, fmt.Errorf("missing deSEC auth-token")
 	}
-
-	// Get a domain to validate authentication
-	if err := c.fetchDomainList(); err != nil {
-		return nil, err
+	if err := c.authenticate(); err != nil {
```
Comment (tlimoncelli) [inline providers/desec/desecProvider.go:31]: Is this going to authenticate once for each domain that calls `DnsProvider()`? 

(It might not... I would test this by setting up a dnsconfig.js with 2 or more domains, and put a Printf statement in this function to see if it prints multiple times)

Please check.

File: providers/desec/protocol.go [hunk 2]
```diff
@@ -58,32 +58,42 @@ type dnssecKey struct {
...
 	err = json.Unmarshal(bodyString, &dr)
 	if err != nil {
 		return err
 	}
-	for _, domain := range dr {
-		//We store the min ttl in the domain index
-		//This will be used for validation and auto correction
-		c.domainIndex[domain.Name] = domain.MinimumTTL
-	}
+	c.domainIndex[dr.Name] = dr.MinimumTTL
```
Comment (tlimoncelli) [inline providers/desec/protocol.go:88]: Please add a comment why dr.MinimumTTL is being used here.

Better yet.... please document in `type desecProvider` what domainIndex represents.

File: providers/desec/desecProvider.go (hunk 1 above)
Comment (D3luxee) [reply providers/desec/desecProvider.go:31]: This is in the initialization function of the provider and is only called once. I've also validated this with printf.

File: providers/desec/protocol.go (hunk 2 above)
Comment (D3luxee) [reply providers/desec/protocol.go:91]: I've added some documentation.

**Comment by D3luxee** [comment]
I think this can be merged when you are ready. This will only fix #996 the issue #1177 will be fixed in another PR.

File: providers/desec/protocol.go [hunk 3]
```diff
@@ -175,6 +176,17 @@ retry:
...
+			waitfor := resp.Header.Get("Retry-After")
+			if waitfor != "" {
+				wait, err := strconv.ParseInt(waitfor, 10, 64)
+				if err == nil {
+					printer.Warnf("Rate limiting.. waiting for %s seconds", waitfor)
+					time.Sleep(time.Duration(wait) * time.Second)
+					goto retry
+				}
+			}
+			printer.Warnf("Rate limiting.. waiting for 500 milliseconds")
```
Comment (peterthomassen) [inline providers/desec/protocol.go:189]: the message is incorrect

File: providers/desec/protocol.go [hunk 4]
```diff
@@ -222,6 +234,17 @@ retry:
...
```
Comment (peterthomassen) [inline providers/desec/protocol.go:247]: the message is incorrect

File: providers/desec/protocol.go (hunk 3 above)
Comment (D3luxee) [reply providers/desec/protocol.go:189]: No its not since this is the fallback, if it can't get the Retry-After header it will wait for 500 milliseconds as it did before.
But if everything works as expected this code and message should never be triggered anymore.

File: providers/desec/protocol.go (hunk 4 above)
Comment (D3luxee) [reply providers/desec/protocol.go:247]: No its not since this is the fallback, if it can't get the Retry-After header it will wait for 500 milliseconds as it did before.
But if everything works as expected this code and message should never be triggered anymore.

**Comment by peterthomassen** [comment]
You may also want to add a cut-off for the wait time, let's say 120 seconds? (In some weird edge cases, it could happen that the daily limit is hit etc., and you probably don't want dnscontrol to stall.)

File: providers/desec/protocol.go (hunk 3 above)
Comment (peterthomassen) [reply providers/desec/protocol.go:189]: My bad, I didn't look thoroughly enough. Sorry!

**Comment by D3luxee** [comment]
> You may also want to add a cut-off for the wait time, let's say 120 seconds? (In some weird edge cases, it could happen that the daily limit is hit etc., and you probably don't want dnscontrol to stall.)

You mean if the Retry-After is like 86400 seconds because its in the daily limit? I'm not sure if thats what you mean :D

**Comment by peterthomassen** [comment]
There is a general limit of 2000 requests per day per user (see docs). If you hit that within two hours (let's say -- but that's almost one request per second), you will have to wait 22 hours (79200 seconds).

I would assume that people don't want to wait for such long time. -- Does dnscontrol have a general timeout parameter? If so, you might want to error out if you can see from the `Retry-After` header that the timeout would be hit while waiting.

**Comment by D3luxee** [comment]
This PR includes various improvements and resolves #996 and #1177 which @tmkis2 just confirmed.

I will now stop to add more commits to this so that @tlimoncelli can complete the review and merge if everything is fine.

**Review by tlimoncelli — APPROVED** [review]

**Comment by tlimoncelli** [comment]
So much to love here!  Thanks for this!  (especially the rate limiting!)
