### PR TITLE
Adding gandi to integration suite. Fixing bugs.

### LINKED ISSUE #35: Gandi does not allow setting apex NS records
Need to remove ns records from desired config like we do for nam.com/cloudflare. 

Show warning if they are for non-gandi.

### LINKED ISSUE #36: Gandi MX priority not diffed properly.

### PR DESCRIPTION
**Pull request by captncraig**
Fixes #35
Fixes #36

### CODE REVIEW

File: providers/gandi/gandiProvider.go [hunk 1]
```diff
@@ -56,48 +59,62 @@ func (c *GandiApi) GetNameservers(domain string) ([]*models.Nameserver, error) {
...
 
-	expectedRecordSets := make([]gandirecord.RecordSet, len(dc.Records))
-	for i, rec := range dc.Records {
-		if rec.Type == "MX" {
-			rec.Target = fmt.Sprintf("%d %s", rec.Priority, rec.Target)
+	expectedRecordSets := make([]gandirecord.RecordSet, 0, len(dc.Records))
+	recordsToKeep := make([]*models.RecordConfig, 0, len(dc.Records))
+	for _, rec := range dc.Records {
+		if rec.TTL < 300 {
+			log.Printf("WARNiNG: Gandi does not support ttls < 300. %s will not be set to %d.", rec.NameFQDN, rec.TTL)
```
Comment (tlimoncelli) [inline providers/gandi/gandiProvider.go]: Typo. WARNiNG

File: providers/gandi/gandiProvider.go [hunk 2]
```diff
@@ -56,48 +59,62 @@ func (c *GandiApi) GetNameservers(domain string) ([]*models.Nameserver, error) {
...
-		expectedRecordSets[i]["name"] = rec.Name
-		expectedRecordSets[i]["value"] = rec.Target
-		expectedRecordSets[i]["ttl"] = rec.TTL
+		if rec.Type == "NS" && rec.Name == "@" {
+			if !strings.HasSuffix(rec.Target, ".gandi.net.") {
+				log.Printf("WARNiNG: Gandi does not support changing apex NS records. %s will not be added.", rec.Target)
+			}
+			continue
+		}
+		rs := gandirecord.RecordSet{}
```
Comment (tlimoncelli) [inline providers/gandi/gandiProvider.go]: Can these next 4 lines be part of the initializer? (not sure myself)
