### PR TITLE
Emit warning in case of label having multiple TTLs

### LINKED ISSUE #1372: DNSControl permits different TTLs within a resource recordset.
For a given DNS label, all the records of the same type need to have the same TTL. (i.e. all the TXT records on foo.bar.com need to have the same TTL.

This isn't enforced by all providers, and DNScontrol doesn't check for out of alignment TTLs.  This confuses providers.

For example:  With the following TXT records, the provider will set the TTL for `TXT'bar.example.com` to be 300, then 9999, then fail when the records are re-checked and the TTL is found to be 9999 instead of 300.

```
D("example.com", FOO,
    // ...
    TXT("bar", "one", TTL(300)),
    TXT("bar", "two", TTL(9999)),
    // ...
)
```

Proposed solution:

1. Add a function call to `auditrecords.go` which checks for misaligned TTLs.
2. Initially make this a warning.  Then make it an error a few releases later.

Tom

### PR DESCRIPTION
**Pull request by costasd**
An RRSet (=label) consisting of multiple records with different TTLs is
something not supported by most providers, and should be avoided.
Furthermore it is deprecated in rfc2181#section-5.2

Emit a warning for now during validation, eventually turning it into a full-blown error.

Fixes #1372

### CODE REVIEW

**Comment by costasd** [comment]
Integration testing works around the validator, so manual tests.

Config:
```
$ cat dnsconfig.js 
/*
   dnsconfig.js: dnscontrol configuration file for #1489
*/

// Providers:

var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var DNS_NS1 = NewDnsProvider('ns1', 'NS1');

D("dnscontrolintegrationnodnssec.io", REG_NONE,
	DefaultTTL('1h'),          // default ttl for records
	NAMESERVER_TTL('1h'),      // default ttl for nameservers
	DnsProvider(DNS_NS1, 1),    // grab 4 nameservers

	A('shouldfail', '1.1.1.1', TTL(300)),
	A('shouldfail', '1.1.1.2', TTL(600)),

	A('shouldsucceed', '1.1.1.1', TTL(600)),
	A('shouldsucceed', '1.1.1.2', TTL(600))
);
```
and execution:
```
$ ~/go/bin/dnscontrol preview 
2022/04/27 22:15:04 printIR.go:88: 1 Validation errors:
2022/04/27 22:15:04 printIR.go:91: WARNING: multiple TTLs detected for: shouldfail.dnscontrolintegrationnodnssec.io A. This should be avoided.
******************** Domain: dnscontrolintegrationnodnssec.io
----- Getting nameservers from: ns1
----- DNS Provider: ns1...
1 correction
#1: MODIFY A shouldfail.dnscontrolintegrationnodnssec.io: (1.1.1.2 ttl=300) -> (1.1.1.2 ttl=600)
----- Registrar: none...
0 corrections
Done. 1 corrections.
```

**Comment by tlimoncelli** [comment]
There's a parse_test that violates the RFCs.  It will need to be fixed before we can merge this.

```
$ go test ./...
?   	github.com/StackExchange/dnscontrol/v3	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/generate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/validate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/cmd/convertzone	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/commands	0.599s
ok  	github.com/StackExchange/dnscontrol/v3/integrationTest	0.265s
ok  	github.com/StackExchange/dnscontrol/v3/models	(cached)
?   	github.com/StackExchange/dnscontrol/v3/pkg/acme	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/diff	(cached)
--- FAIL: TestParsedFiles (0.44s)
    --- FAIL: TestParsedFiles/012-duration.js (0.01s)
        js_test.go:91: multiple TTLs detected for: foo.com A. This should be avoided.
FAIL
FAIL	github.com/StackExchange/dnscontrol/v3/pkg/js	0.744s
?   	github.com/StackExchange/dnscontrol/v3/pkg/nameservers	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/natsort	(cached)
ok  	github.com/StackExchange/dnscontrol/v3/pkg/normalize	0.148s
?   	github.com/StackExchange/dnscontrol/v3/pkg/notifications	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/prettyzone	(cached)
...
```

File: pkg/normalize/validate.go [hunk 1]
```diff
@@ -553,6 +555,35 @@ func checkDuplicates(records []*models.RecordConfig) (errs []error) {
...
+		label := fmt.Sprintf("%s %s", r.GetLabelFQDN(), r.Type)
+
+		// if we have more records for a given label, append their TTLs here, but deduplicate slice before returning it
+		m[label] = uniq(append(m[label], r.TTL))
+
+		// if after the uniq() pass we still have more than one ttl, it means we have multiple TTLs for that label
+		if len(m[label]) > 1 {
+			errs = append(errs, Warning{fmt.Errorf("multiple TTLs detected for: %s. This should be avoided.", label)})
+		}
+	}
```
Comment (tlimoncelli) [inline pkg/normalize/validate.go:583]: I noticed that if there are many records each with unique TTLs, the warning message appears n-1 times.  This might be by design.  It might be better to have one warning per label+rtype.

To do that, I suggest 2 loops.  The first one does builds up the lists of TTLs per label+rtype; the second calls uniq() on the list and generates the warning if len>1.

Here's my test:

```
$ git diff
...
+  //
+    A("testttl", IP_MAIN, TTL(400)),
+    A("testttl", IP_MAIN, TTL(401)),
+    A("testttl", IP_MAIN, TTL(402)),
+    A("testttl", IP_MAIN, TTL(403)),
+  //
...

$ dnscontrol preview --domains whatexit.org
2022/04/29 15:41:56 printIR.go:88: 3 Validation errors:
2022/04/29 15:41:56 printIR.go:91: WARNING: multiple TTLs detected for: testttl.whatexit.org A. This should be avoided.
2022/04/29 15:41:56 printIR.go:91: WARNING: multiple TTLs detected for: testttl.whatexit.org A. This should be avoided.
2022/04/29 15:41:56 printIR.go:91: WARNING: multiple TTLs detected for: testttl.whatexit.org A. This should be avoided.
```

Comment (costasd) [reply pkg/normalize/validate.go:583]: good one, I'll change it!

**Review by tlimoncelli — APPROVED** [review]

**Comment by tlimoncelli** [comment]
Thanks for fixing this bug!  A lot of confusion gets caused by this, which will now be avoided.
