### PR TITLE
TRANSIP: Fixed integration tests: Edge cases and TXT records fixed

### LINKED ISSUE #2330: TRANSIP builds breaking
@blackshadev 

I think you know about this already, but just in case...

(diff1)

```
~/git/dnscontrol/integrationTest$ go test -v -verbose -provider TRANSIP
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/dnscontrol.zone
=== RUN   TestDNSProviders/dnscontrol.zone/Clean_Slate:Empty
=== RUN   TestDNSProviders/dnscontrol.zone/00:A:Create_A
    integration_test.go:230: 
        + CREATE A testa.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/00:A:Change_A_target
    integration_test.go:230: 
        ± MODIFY A testa.dnscontrol.zone: (1.1.1.1 ttl=300) -> (3.3.3.3 ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty
    integration_test.go:230: 
        - DELETE A testa.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/01:Apex:Create_A
    integration_test.go:230: 
        + CREATE A dnscontrol.zone 2.2.2.2 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/01:Apex:Change_A_target
    integration_test.go:230: 
        ± MODIFY A dnscontrol.zone: (2.2.2.2 ttl=300) -> (4.4.4.4 ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#01
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 4.4.4.4 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/02:Protocol-Wildcard:Create_wildcard
    integration_test.go:230: 
        + CREATE A *.dnscontrol.zone 3.3.3.3 ttl=300
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 5.5.5.5 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/02:Protocol-Wildcard:Delete_wildcard
    integration_test.go:230: 
        - DELETE A *.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#02
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 5.5.5.5 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/03:CNAME:Create_a_CNAME
    integration_test.go:230: 
        + CREATE CNAME testcname.dnscontrol.zone www.google.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/03:CNAME:Change_CNAME_target
    integration_test.go:230: 
        ± MODIFY CNAME testcname.dnscontrol.zone: (www.google.com. ttl=300) -> (www.yahoo.com. ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#03
    integration_test.go:230: 
        - DELETE CNAME testcname.dnscontrol.zone www.yahoo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/04:MX:Create_MX
    integration_test.go:230: 
        + CREATE MX testmx.dnscontrol.zone 5 foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/04:MX:Change_MX_target
    integration_test.go:230: 
        ± MODIFY MX testmx.dnscontrol.zone: (5 foo.com. ttl=300) -> (5 bar.com. ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/04:MX:Change_MX_p
    integration_test.go:230: 
        ± MODIFY MX testmx.dnscontrol.zone: (5 bar.com. ttl=300) -> (100 bar.com. ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#04
    integration_test.go:230: 
        - DELETE MX testmx.dnscontrol.zone 100 bar.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/05:TXT:Create_TXT
    integration_test.go:230: 
        + CREATE TXT testtxt.dnscontrol.zone "simple" ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/05:TXT:Change_TXT_target
    integration_test.go:230: 
        ± MODIFY TXT testtxt.dnscontrol.zone: ("simple" ttl=300) -> ("changed" ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#05
    integration_test.go:230: 
        - DELETE TXT testtxt.dnscontrol.zone "changed" ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:CreateManyAtLabel
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.1.1.1 ttl=300
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 2.2.2.2 ttl=300
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Empty
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 1.1.1.1 ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 2.2.2.2 ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Create_an_A_record
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Add_at_label1
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 2.2.2.2 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Add_at_label2
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#06
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 1.1.1.1 ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 2.2.2.2 ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 3.3.3.3 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:CreateManyTypesAtLabel
    integration_test.go:230: 
        + CREATE MX testmx.dnscontrol.zone 5 foo.com. ttl=300
    integration_test.go:230: 
        + CREATE MX testmx.dnscontrol.zone 100 bar.com. ttl=300
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Empty
    integration_test.go:230: 
        - DELETE MX testmx.dnscontrol.zone 100 bar.com. ttl=300
    integration_test.go:230: 
        - DELETE MX testmx.dnscontrol.zone 5 foo.com. ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Create_an_A_record
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Add_Type_At_Label
    integration_test.go:230: 
        + CREATE MX testmx.dnscontrol.zone 5 foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Add_Type_At_Label#01
    integration_test.go:230: 
        + CREATE MX testmx.dnscontrol.zone 100 bar.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#07
    integration_test.go:230: 
        - DELETE MX testmx.dnscontrol.zone 100 bar.com. ttl=300
    integration_test.go:230: 
        - DELETE MX testmx.dnscontrol.zone 5 foo.com. ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 1.1.1.1 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/08:Attl:Create_Arc
    integration_test.go:230: 
        + CREATE A testa.dnscontrol.zone 1.1.1.1 ttl=333
=== RUN   TestDNSProviders/dnscontrol.zone/08:Attl:Change_TTL
    integration_test.go:230: 
        ± MODIFY A testa.dnscontrol.zone: (1.1.1.1 ttl=333) -> (1.1.1.1 ttl=999)[1/2]
    integration_test.go:230: 
        ± MODIFY A testa.dnscontrol.zone: (1.1.1.1 ttl=333) -> (1.1.1.1 ttl=999)[2/2]
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#08
    integration_test.go:230: 
        - DELETE A testa.dnscontrol.zone 1.1.1.1 ttl=999
=== RUN   TestDNSProviders/dnscontrol.zone/09:TTL:Start
    integration_test.go:230: 
        + CREATE A dnscontrol.zone 8.8.8.8 ttl=666
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 5.6.7.8 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/09:TTL:Change_a_ttl
    integration_test.go:230: 
        ± MODIFY A dnscontrol.zone: (8.8.8.8 ttl=666) -> (8.8.8.8 ttl=1000)[1/2]
    integration_test.go:230: 
        ± MODIFY A dnscontrol.zone: (8.8.8.8 ttl=666) -> (8.8.8.8 ttl=1000)[2/2]
=== RUN   TestDNSProviders/dnscontrol.zone/09:TTL:Change_single_target_from_set
    integration_test.go:230: 
        ± MODIFY A www.dnscontrol.zone: (1.2.3.4 ttl=300) -> (2.2.2.2 ttl=300)
    integration_test.go:235: Multiple matches found for DNS entry 'www 300 A'
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#09
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 8.8.8.8 ttl=1000
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 5.6.7.8 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/10:add_to_label_and_change_orig_ttl:Setup
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 5.6.7.8 ttl=400
=== RUN   TestDNSProviders/dnscontrol.zone/10:add_to_label_and_change_orig_ttl:Add_at_same_label,_new_ttl
    integration_test.go:230: 
        + CREATE A www.dnscontrol.zone 1.2.3.4 ttl=700
    integration_test.go:235: the expire of all records in an rrset must be all the same: www 400 A 5.6.7.8
        the expire of all records in an rrset must be all the same: www 700 A 1.2.3.4
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#10
    integration_test.go:230: 
        - DELETE A www.dnscontrol.zone 5.6.7.8 ttl=400
=== RUN   TestDNSProviders/dnscontrol.zone/11:TypeChange:Create_A
    integration_test.go:230: 
        + CREATE A foo.dnscontrol.zone 1.2.3.4 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/11:TypeChange:Change_to_MX
    integration_test.go:230: 
        - DELETE A foo.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        + CREATE MX foo.dnscontrol.zone 5 mx.google.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/11:TypeChange:Change_back_to_A
    integration_test.go:230: 
        - DELETE MX foo.dnscontrol.zone 5 mx.google.com. ttl=300
    integration_test.go:230: 
        + CREATE A foo.dnscontrol.zone 4.5.6.7 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#11
    integration_test.go:230: 
        - DELETE A foo.dnscontrol.zone 4.5.6.7 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Create_a_CNAME
    integration_test.go:230: 
        + CREATE CNAME foo.dnscontrol.zone google.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Change_to_A_record
    integration_test.go:230: 
        - DELETE CNAME foo.dnscontrol.zone google.com. ttl=300
    integration_test.go:230: 
        + CREATE A foo.dnscontrol.zone 1.2.3.4 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Change_back_to_CNAME
    integration_test.go:230: 
        - DELETE A foo.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        + CREATE CNAME foo.dnscontrol.zone google2.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#12
    integration_test.go:230: 
        - DELETE CNAME foo.dnscontrol.zone google2.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/13:CNAME:Record_pointing_to_@
    integration_test.go:230: 
        + CREATE CNAME foo.dnscontrol.zone dnscontrol.zone. ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 CNAME dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#13
=== RUN   TestDNSProviders/dnscontrol.zone/14:MX:Record_pointing_to_@
    integration_test.go:230: 
        + CREATE MX foo.dnscontrol.zone 8 dnscontrol.zone. ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 MX 8 dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#14
=== RUN   TestDNSProviders/dnscontrol.zone/15:NS:NS_for_subdomain
    integration_test.go:230: 
        + CREATE NS xyz.dnscontrol.zone ns2.foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/15:NS:Dual_NS_for_subdomain
    integration_test.go:230: 
        + CREATE NS xyz.dnscontrol.zone ns1.foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/15:NS:NS_Record_pointing_to_@
    integration_test.go:230: 
        - DELETE NS xyz.dnscontrol.zone ns1.foo.com. ttl=300
    integration_test.go:230: 
        - DELETE NS xyz.dnscontrol.zone ns2.foo.com. ttl=300
    integration_test.go:230: 
        + CREATE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        + CREATE NS foo.dnscontrol.zone dnscontrol.zone. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#15
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/16:complex_TXT:TXT_with_1_single-quote
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#16
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/17:Case_Sensitivity:Create_CAPS
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#17
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/18:testByLabel:initial
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#18
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/19:testByRecordSet:initial
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#19
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/20:IDNA:Internationalized_name
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#20
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/21:IDNAs_in_CNAME_targets:IDN_CNAME_AND_Target
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#21
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/22:pager101:99_records
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#22
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/23:pager601_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/24:pager1201_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/25:CAA:CAA_record
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#23
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/26:LOC_***SKIPPED(CanUseLOC_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/27:NAPTR:NAPTR_record
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#24
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/28:PTR_***SKIPPED(CanUsePTR_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/29:SOA_***SKIPPED(CanUseSOA_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/30:SRV:SRV_record
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#25
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/31:SRV:Create_SRV333
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#26
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/32:SSHFP:SSHFP_record
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#27
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/33:TLSA:TLSA_record
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#28
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/34:DS_***SKIPPED(CanUseDS_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/35:DS_(children_only)_***SKIPPED(CanUseDSForChildren_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/36:DS_(children_only)_CLOUDNS_***SKIPPED(CanUseDSForChildren_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/37:ALIAS:ALIAS_at_root
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#29
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/38:AZURE_ALIAS_A_***SKIPPED(CanUseAzureAlias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/39:AZURE_ALIAS_CNAME_***SKIPPED(CanUseAzureAlias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/40:R53_ALIAS2_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/41:R53_ALIAS_ORDER_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/42:R53_ALIAS_CNAME_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/43:R53_ALIAS_Loop_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/44:R53_alias_pre-existing_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/45:CF_REDIRECT_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/46:CF_PROXY_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/47:CF_WORKER_ROUTE_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/48:NS1_URLFWD_tests_***SKIPPED(disabled_by_only)***:Empty
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/49:IGNORE_NAME_function:Create_some_records
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#30
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:235: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 NS dnscontrol.zone.
=== RUN   TestDNSProviders/dnscontrol.zone/50:IGNORE_NAME_apex:Create_some_records
    integration_test.go:230: 
        - DELETE NS foo.dnscontrol.zone dnscontrol.zone. ttl=300
    integration_test.go:230: 
        + CREATE A bar.dnscontrol.zone 2.4.6.8 ttl=300
    integration_test.go:230: 
        + CREATE TXT bar.dnscontrol.zone "stringbar" ttl=300
    integration_test.go:230: 
        + CREATE TXT dnscontrol.zone "simple" ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/50:IGNORE_NAME_apex:Add_a_new_record_-_ignoring_apex
    integration_test.go:230: 
        - DELETE A dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        - DELETE TXT dnscontrol.zone "simple" ttl=300
    integration_test.go:230: 
        + CREATE A added.dnscontrol.zone 4.6.8.9 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#31
    integration_test.go:230: 
        - DELETE A added.dnscontrol.zone 4.6.8.9 ttl=300
    integration_test.go:230: 
        - DELETE A bar.dnscontrol.zone 2.4.6.8 ttl=300
    integration_test.go:230: 
        - DELETE TXT bar.dnscontrol.zone "stringbar" ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Create_some_records
    integration_test.go:230: 
        + CREATE CNAME bar.dnscontrol.zone test.bar.com. ttl=300
    integration_test.go:230: 
        + CREATE CNAME foo.dnscontrol.zone test.foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Add_a_new_record_-_ignoring_test.foo.com.
    integration_test.go:230: 
        ± MODIFY CNAME bar.dnscontrol.zone: (test.bar.com. ttl=300) -> (bar.foo.com. ttl=300)
=== RUN   TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Empty
    integration_test.go:230: 
        - DELETE CNAME bar.dnscontrol.zone bar.foo.com. ttl=300
    integration_test.go:230: 
        - DELETE CNAME foo.dnscontrol.zone test.foo.com. ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Create_some_records#01
    integration_test.go:230: 
        + CREATE CNAME bar.foo.dnscontrol.zone a.b.foo.com. ttl=300
    integration_test.go:230: 
        + CREATE A test.foo.dnscontrol.zone 1.2.3.4 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Add_a_new_record_-_ignoring_**.foo.com._targets
    integration_test.go:230: 
        - DELETE A test.foo.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        + CREATE A bar.dnscontrol.zone 1.2.3.4 ttl=300
=== RUN   TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#32
    integration_test.go:230: 
        - DELETE A bar.dnscontrol.zone 1.2.3.4 ttl=300
    integration_test.go:230: 
        - DELETE CNAME bar.foo.dnscontrol.zone a.b.foo.com. ttl=300
--- FAIL: TestDNSProviders (290.24s)
    --- FAIL: TestDNSProviders/dnscontrol.zone (290.24s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Clean_Slate:Empty (0.33s)
        --- PASS: TestDNSProviders/dnscontrol.zone/00:A:Create_A (2.23s)
        --- PASS: TestDNSProviders/dnscontrol.zone/00:A:Change_A_target (2.24s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty (1.99s)
        --- PASS: TestDNSProviders/dnscontrol.zone/01:Apex:Create_A (3.33s)
        --- PASS: TestDNSProviders/dnscontrol.zone/01:Apex:Change_A_target (2.79s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#01 (2.70s)
        --- PASS: TestDNSProviders/dnscontrol.zone/02:Protocol-Wildcard:Create_wildcard (7.74s)
        --- PASS: TestDNSProviders/dnscontrol.zone/02:Protocol-Wildcard:Delete_wildcard (2.71s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#02 (2.70s)
        --- PASS: TestDNSProviders/dnscontrol.zone/03:CNAME:Create_a_CNAME (2.96s)
        --- PASS: TestDNSProviders/dnscontrol.zone/03:CNAME:Change_CNAME_target (3.12s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#03 (1.92s)
        --- PASS: TestDNSProviders/dnscontrol.zone/04:MX:Create_MX (2.40s)
        --- PASS: TestDNSProviders/dnscontrol.zone/04:MX:Change_MX_target (2.71s)
        --- PASS: TestDNSProviders/dnscontrol.zone/04:MX:Change_MX_p (2.43s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#04 (2.47s)
        --- PASS: TestDNSProviders/dnscontrol.zone/05:TXT:Create_TXT (2.70s)
        --- PASS: TestDNSProviders/dnscontrol.zone/05:TXT:Change_TXT_target (2.70s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#05 (2.26s)
        --- PASS: TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:CreateManyAtLabel (6.12s)
        --- PASS: TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Empty (6.54s)
        --- PASS: TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Create_an_A_record (3.16s)
        --- PASS: TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Add_at_label1 (2.68s)
        --- PASS: TestDNSProviders/dnscontrol.zone/06:ManyAtOnce:Add_at_label2 (2.36s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#06 (6.15s)
        --- PASS: TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:CreateManyTypesAtLabel (6.99s)
        --- PASS: TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Empty (6.71s)
        --- PASS: TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Create_an_A_record (2.31s)
        --- PASS: TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Add_Type_At_Label (3.21s)
        --- PASS: TestDNSProviders/dnscontrol.zone/07:manyTypesAtOnce:Add_Type_At_Label#01 (3.19s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#07 (6.03s)
        --- PASS: TestDNSProviders/dnscontrol.zone/08:Attl:Create_Arc (2.89s)
        --- PASS: TestDNSProviders/dnscontrol.zone/08:Attl:Change_TTL (4.89s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#08 (2.85s)
        --- PASS: TestDNSProviders/dnscontrol.zone/09:TTL:Start (6.64s)
        --- PASS: TestDNSProviders/dnscontrol.zone/09:TTL:Change_a_ttl (4.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/09:TTL:Change_single_target_from_set (0.84s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#09 (6.41s)
        --- PASS: TestDNSProviders/dnscontrol.zone/10:add_to_label_and_change_orig_ttl:Setup (2.37s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/10:add_to_label_and_change_orig_ttl:Add_at_same_label,_new_ttl (1.02s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#10 (2.34s)
        --- PASS: TestDNSProviders/dnscontrol.zone/11:TypeChange:Create_A (2.72s)
        --- PASS: TestDNSProviders/dnscontrol.zone/11:TypeChange:Change_to_MX (4.37s)
        --- PASS: TestDNSProviders/dnscontrol.zone/11:TypeChange:Change_back_to_A (4.57s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#11 (2.42s)
        --- PASS: TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Create_a_CNAME (3.40s)
        --- PASS: TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Change_to_A_record (4.95s)
        --- PASS: TestDNSProviders/dnscontrol.zone/12:TypeChangeHard:Change_back_to_CNAME (4.80s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#12 (2.42s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/13:CNAME:Record_pointing_to_@ (0.97s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#13 (0.33s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/14:MX:Record_pointing_to_@ (0.95s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#14 (0.36s)
        --- PASS: TestDNSProviders/dnscontrol.zone/15:NS:NS_for_subdomain (2.85s)
        --- PASS: TestDNSProviders/dnscontrol.zone/15:NS:Dual_NS_for_subdomain (2.61s)
        --- PASS: TestDNSProviders/dnscontrol.zone/15:NS:NS_Record_pointing_to_@ (9.33s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#15 (1.04s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/16:complex_TXT:TXT_with_1_single-quote (1.02s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#16 (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/17:Case_Sensitivity:Create_CAPS (1.04s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#17 (0.94s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/18:testByLabel:initial (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#18 (0.99s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/19:testByRecordSet:initial (1.01s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#19 (1.00s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/20:IDNA:Internationalized_name (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#20 (1.05s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/21:IDNAs_in_CNAME_targets:IDN_CNAME_AND_Target (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#21 (0.99s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/22:pager101:99_records (1.02s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#22 (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/23:pager601_***SKIPPED(disabled_by_only)***:Empty (1.02s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/24:pager1201_***SKIPPED(disabled_by_only)***:Empty (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/25:CAA:CAA_record (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#23 (1.03s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/26:LOC_***SKIPPED(CanUseLOC_not_supported)***:Empty (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/27:NAPTR:NAPTR_record (1.04s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#24 (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/28:PTR_***SKIPPED(CanUsePTR_not_supported)***:Empty (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/29:SOA_***SKIPPED(CanUseSOA_not_supported)***:Empty (0.94s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/30:SRV:SRV_record (1.00s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#25 (0.99s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/31:SRV:Create_SRV333 (1.02s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#26 (1.04s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/32:SSHFP:SSHFP_record (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#27 (0.95s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/33:TLSA:TLSA_record (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#28 (1.03s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/34:DS_***SKIPPED(CanUseDS_not_supported)***:Empty (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/35:DS_(children_only)_***SKIPPED(CanUseDSForChildren_not_supported)***:Empty (0.97s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/36:DS_(children_only)_CLOUDNS_***SKIPPED(CanUseDSForChildren_not_supported)***:Empty (0.99s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/37:ALIAS:ALIAS_at_root (0.97s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#29 (0.98s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/38:AZURE_ALIAS_A_***SKIPPED(CanUseAzureAlias_not_supported)***:Empty (1.00s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/39:AZURE_ALIAS_CNAME_***SKIPPED(CanUseAzureAlias_not_supported)***:Empty (1.02s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/40:R53_ALIAS2_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty (0.99s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/41:R53_ALIAS_ORDER_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/42:R53_ALIAS_CNAME_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty (1.00s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/43:R53_ALIAS_Loop_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty (1.03s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/44:R53_alias_pre-existing_***SKIPPED(CanUseRoute53Alias_not_supported)***:Empty (0.97s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/45:CF_REDIRECT_***SKIPPED(disabled_by_only)***:Empty (0.96s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/46:CF_PROXY_***SKIPPED(disabled_by_only)***:Empty (1.07s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/47:CF_WORKER_ROUTE_***SKIPPED(disabled_by_only)***:Empty (1.00s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/48:NS1_URLFWD_tests_***SKIPPED(disabled_by_only)***:Empty (1.01s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/49:IGNORE_NAME_function:Create_some_records (0.97s)
        --- FAIL: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#30 (1.03s)
        --- PASS: TestDNSProviders/dnscontrol.zone/50:IGNORE_NAME_apex:Create_some_records (8.95s)
        --- PASS: TestDNSProviders/dnscontrol.zone/50:IGNORE_NAME_apex:Add_a_new_record_-_ignoring_apex (6.15s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#31 (6.27s)
        --- PASS: TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Create_some_records (5.37s)
        --- PASS: TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Add_a_new_record_-_ignoring_test.foo.com. (2.44s)
        --- PASS: TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Empty (4.32s)
        --- PASS: TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Create_some_records#01 (4.93s)
        --- PASS: TestDNSProviders/dnscontrol.zone/51:IGNORE_TARGET_function:Add_a_new_record_-_ignoring_**.foo.com._targets (4.95s)
        --- PASS: TestDNSProviders/dnscontrol.zone/Post_cleanup:Empty#32 (3.98s)
=== RUN   TestDualProviders
    integration_test.go:334: Skipping.  DocDualHost == Cannot
--- SKIP: TestDualProviders (0.73s)
=== RUN   TestNameserverDots
    integration_test.go:392: Skipping.  DocDualHost == Cannot
--- SKIP: TestNameserverDots (0.69s)
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v3/integrationTest	291.986s

```

### LINKED ISSUE #2670: TRANSIP tests breaking
Tests were reactivated but I see a few tests are failing.  I did some basic triage but couldn't isolate the problem.

I've disabled the tests.  To re-activate them, set TRANSIP_DOMAIN to dnscontrol.nl in GHA.

```
$ cd ~/git/dnscontrol/integrationTest
$ go test  -provider TRANSIP -start 15 -end 15
--- FAIL: TestDNSProviders (2.54s)
    --- FAIL: TestDNSProviders/dnscontrol.nl (2.53s)
        --- FAIL: TestDNSProviders/dnscontrol.nl/15:MX:Record_pointing_to_@ (0.92s)
            integration_test.go:252: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 MX 8 dnscontrol.nl.
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v4/integrationTest	4.330s
$ 
```

CC @blackshadev @cafferata

### PR DESCRIPTION
**Pull request by blackshadev**
# What

Fixes integration tests for trans IP. Fixes #2670 and fixes #2330

- Remove slashes on quoted strings
- Add A records to integration tests which were missing a base record
- Separate ALIAS integration tests, TransIP support ALIAS only on apex records
- Change the update record set using recreate  to not delete the whole record set first, but try and diff the records one by one.
- Disable the pager integration tests as they take ages to complete

### CODE REVIEW

File: providers/transip/transipProvider.go [hunk 1]
```diff
@@ -325,6 +348,6 @@ func getTargetRecordContent(rc *models.RecordConfig) string {
 	case "SRV":
 		return fmt.Sprintf("%d %d %d %s", rc.SrvPriority, rc.SrvWeight, rc.SrvPort, rc.GetTargetField())
 	default:
-		return models.StripQuotes(rc.GetTargetCombined())
+		return models.RemoveSlashes(models.StripQuotes(rc.GetTargetCombined()))
```
Comment (tlimoncelli) [inline providers/transip/transipProvider.go:351]: Is models.RemoveSlashes() only needed to TXT records?  If so, move that to a `case "TXT"` statement.

File: models/slashes.go [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package models
```
Comment (tlimoncelli) [inline models/slashes.go:1]: Please move this to `providers/transip`.  While this function seems re-usable by other providers, I'd rather have each provider be independent as much as possible.

File: providers/transip/transipProvider.go (hunk 1 above)
Comment (blackshadev) [reply providers/transip/transipProvider.go]: I believe so... added it.

File: models/slashes.go [hunk 3]
```diff
@@ -0,0 +1,10 @@
...
+
+import (
+	"regexp"
+)
+
+func RemoveSlashes(s string) string {
+	m := regexp.MustCompile("(?:\\\\(\\\\)+)|(?:\\\\)")
```
[the remark this answers is not in the document]
Comment (blackshadev) [reply models/slashes.go]: Ok, done. Go didn't accept `removeSlashesRE := regexp.MustCompile("(?:\\\\(\\\\)+)|(?:\\\\)")`. But did accept  `var removeSlashesRE = regexp.MustCompile("(?:\\\\(\\\\)+)|(?:\\\\)")`
