### PR TITLE
TESTING: Don't skip other tests when test failed

### LINKED ISSUE #2244: CLOUDNS: NS Record pointing to @ integration test failing
```
# go test -v -verbose -provider CLOUDNS -start 15 -end 15
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/example.com
=== RUN   TestDNSProviders/example.com/Clean_Slate:Empty
=== RUN   TestDNSProviders/example.com/15:NS:NS_for_subdomain
    integration_test.go:223:
        + CREATE NS xyz.example.com ns2.foo.com. ttl=300
=== RUN   TestDNSProviders/example.com/15:NS:Dual_NS_for_subdomain
    integration_test.go:223:
        + CREATE NS xyz.example.com ns1.foo.com. ttl=300
=== RUN   TestDNSProviders/example.com/15:NS:NS_Record_pointing_to_@
    integration_test.go:223:
        - DELETE NS xyz.example.com ns1.foo.com. ttl=300, ClouDNS ID: 283378001
    integration_test.go:223:
        - DELETE NS xyz.example.com ns2.foo.com. ttl=300, ClouDNS ID: 283377999
    integration_test.go:223:
        + CREATE NS foo.example.com example.com. ttl=300
    integration_test.go:227: failed create record (ClouDNS): ClouDNS API error: The NS record needs to be pointed to a hostname that has an A or an AAAA record. URL:api.cloudns.net/dns/add-record.json?auth-id=**REDACTED**&auth-password=**REDACTED**&domain-name=example.com&host=foo&record=example.com&record-type=NS&sub-auth-id=&ttl=300
=== RUN   TestDNSProviders/example.com/Post_cleanup:Empty
--- FAIL: TestDNSProviders (2.62s)
    --- FAIL: TestDNSProviders/example.com (2.31s)
        --- PASS: TestDNSProviders/example.com/Clean_Slate:Empty (0.23s)
        --- PASS: TestDNSProviders/example.com/15:NS:NS_for_subdomain (0.58s)
        --- PASS: TestDNSProviders/example.com/15:NS:Dual_NS_for_subdomain (0.57s)
        --- FAIL: TestDNSProviders/example.com/15:NS:NS_Record_pointing_to_@ (0.58s)
        --- PASS: TestDNSProviders/example.com/Post_cleanup:Empty (0.23s)
=== RUN   TestDualProviders
    integration_test.go:318: Skipping.  DocDualHost == Cannot
--- SKIP: TestDualProviders (0.26s)
FAIL
exit status 1
FAIL    github.com/StackExchange/dnscontrol/v3/integrationTest  2.887s
```

issue root

https://github.com/StackExchange/dnscontrol/blob/f700184e3803c9b60cf43dc5960155a39da721cf/providers/cloudns/cloudnsProvider.go#L158-L165

As I can see here, A/AAAA records need to be created before NS, NS records need to be created before DS

Self-assigned, will create a PR soon.

### PR DESCRIPTION
**Pull request by imlonghao**
When I fix, #2244, another different integration test failed shows up.

It bothers me why the first time only one integration test failed shows up.

Then I found out that when one test case failed, the rest test group only run the first test case, then break out of the for loop.

I see no reason why we break out of the for loop when a test case failed.

Before this PR,

```
# go test -v -verbose -provider CLOUDNS -start 15 -end 16
--- FAIL: TestDNSProviders (4.98s)
    --- FAIL: TestDNSProviders/example.com (4.39s)
        --- PASS: TestDNSProviders/example.com/Clean_Slate:Empty (0.28s)
        --- PASS: TestDNSProviders/example.com/15:NS:NS_for_subdomain (0.76s)
        --- PASS: TestDNSProviders/example.com/15:NS:Dual_NS_for_subdomain (0.75s)
        --- FAIL: TestDNSProviders/example.com/15:NS:NS_Record_pointing_to_@ (0.81s)
        --- PASS: TestDNSProviders/example.com/Post_cleanup:Empty (0.28s)
        --- PASS: TestDNSProviders/example.com/16:complex_TXT:TXT_with_1_single-quote (0.75s)
        --- PASS: TestDNSProviders/example.com/Post_cleanup:Empty#01 (0.48s)
=== RUN   TestDualProviders
    integration_test.go:318: Skipping.  DocDualHost == Cannot
--- SKIP: TestDualProviders (2.10s)
FAIL
exit status 1
FAIL    github.com/StackExchange/dnscontrol/v3/integrationTest  7.085s
```

Apply this PR,

```
# go test -v -verbose -provider CLOUDNS -start 15 -end 16
--- FAIL: TestDNSProviders (4.00s)
    --- FAIL: TestDNSProviders/example.com (3.82s)
        --- PASS: TestDNSProviders/example.com/Clean_Slate:Empty (0.22s)
        --- PASS: TestDNSProviders/example.com/15:NS:NS_for_subdomain (0.56s)
        --- PASS: TestDNSProviders/example.com/15:NS:Dual_NS_for_subdomain (0.56s)
        --- FAIL: TestDNSProviders/example.com/15:NS:NS_Record_pointing_to_@ (0.56s)
        --- PASS: TestDNSProviders/example.com/Post_cleanup:Empty (0.22s)
        --- PASS: TestDNSProviders/example.com/16:complex_TXT:TXT_with_1_single-quote (0.56s)
        --- SKIP: TestDNSProviders/example.com/16:complex_TXT:TXT_with_1_backtick (0.00s)
        --- SKIP: TestDNSProviders/example.com/16:complex_TXT:TXT_with_1_double-quotes (0.00s)
        --- SKIP: TestDNSProviders/example.com/16:complex_TXT:TXT_with_2_double-quotes (0.00s)
        --- PASS: TestDNSProviders/example.com/16:complex_TXT:a_TXT_with_interior_ws (0.67s)
        --- SKIP: TestDNSProviders/example.com/16:complex_TXT:TXT_with_ws_at_end (0.00s)
        --- PASS: TestDNSProviders/example.com/Post_cleanup:Empty#01 (0.34s)
=== RUN   TestDualProviders
    integration_test.go:318: Skipping.  DocDualHost == Cannot
--- SKIP: TestDualProviders (0.26s)
FAIL
exit status 1
FAIL    github.com/StackExchange/dnscontrol/v3/integrationTest  4.270s
```

### CODE REVIEW

**Comment by imlonghao** [comment]
I'm more prefer the latter since I don't want to do some major changes to the global integration test.
Besides, the integration tests should be PASSED most times, so this is not an urgent need, we can do that later.

I still want to remove the `if t.Failed()` line, use the result from `makeChanges` instead.
Now when a test case failed, the rest from the same test group will be skipped, and the failure doesn't affect other test groups.
This seems more reasonable.

As for the `TODO:` note, can you add a commit to this PR for me?
I'm not a native English speaker, I'm afraid my note will cause some misunderstanding in the future.

File: integrationTest/integration_test.go [hunk 1]
```diff
@@ -286,11 +286,10 @@ func runTests(t *testing.T, prv providers.DNSServiceProvider, domainName string,
 
 		for _, tst := range group.tests {
 
-			makeChanges(t, prv, dc, tst, fmt.Sprintf("%02d:%s", gIdx, group.Desc), true, origConfig)
-
-			if t.Failed() {
+			if ok := makeChanges(t, prv, dc, tst, fmt.Sprintf("%02d:%s", gIdx, group.Desc), true, origConfig); !ok {
```
Comment (tlimoncelli) [inline integrationTest/integration_test.go:289]:
```suggestion
// TODO(tlim): This is the old version. It skipped the remaining tc() statements if one failed.
// The new code continues to test the remaining tc() statements.  Keeping this as a comment
// in case we ever want to do something similar.
// https://github.com/StackExchange/dnscontrol/pull/2252#issuecomment-1492204409
//      makeChanges(t, prv, dc, tst, fmt.Sprintf("%02d:%s", gIdx, group.Desc), true, origConfig)
//      if t.Failed() {
//        break
//      }
			if ok := makeChanges(t, prv, dc, tst, fmt.Sprintf("%02d:%s", gIdx, group.Desc), true, origConfig); !ok {
```

**Comment by imlonghao** [comment]
I have run `go fmt ./...` for your comment.

> The new code continues to test the remaining tc() statements.

No, the new code still skips the remaining `tc()` statements in the same `testgroup()`.

( I'm not sure whether you understand this change. Do you want me to explain again? )

**Comment by tlimoncelli** [comment]
Oh!  No, your language was fine. I mis-read it!  My apologies.
