### PR TITLE
CLOUDFLARE: Add LOC support

### LINKED ISSUE #2798: CLOUDFLAREAPI: LOC supported by CF but not by integration
**Describe the bug**
The LOC record is supported by Cloudflare, but not by the integration.
https://github.com/StackExchange/dnscontrol/blob/56220fba5f94b13c935dea782682f4fd45d6d0a1/providers/cloudflare/cloudflareProvider.go#L46

**Expected behavior**
Cloudflare supports LOC records, I would assume that the DNSControl integration would also support them.
I'm hoping this may be as simple as switching `Cannot` to `Can`.

LOC is listed as a valid type in the Cloudflare API: https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-list-dns-records

**DNS Provider**
 - Cloudflare

### PR DESCRIPTION
**Pull request by kevinji**
Fixes #2798.

I tested this locally and it seems to update the `LOC` record correctly.

### CODE REVIEW

File: models/t_loc.go [hunk 1]
```diff
@@ -99,26 +99,20 @@ func (rc *RecordConfig) calculateLOCFields(d1 uint8, m1 uint8, s1 float32, ns st
...
-	const LOCEquator uint64 = 0x80000000       // 1 << 31 // RFC 1876, Section 2.
-	const LOCPrimeMeridian uint64 = 0x80000000 // 1 << 31 // RFC 1876, Section 2.
-	const LOCHours uint32 = 60 * 1000
-	const LOCDegrees = 60 * LOCHours
-	const LOCAltitudeBase int32 = 100000
-
-	lat := uint64((uint32(d1) * LOCDegrees) + (uint32(m1) * LOCHours) + uint32(s1*1000))
-	lon := uint64((uint32(d2) * LOCDegrees) + (uint32(m2) * LOCHours) + uint32(s2*1000))
+	lat := uint32(d1)*dns.LOC_DEGREES + uint32(m1)*dns.LOC_HOURS + uint32(s1*1000)
+	lon := uint32(d2)*dns.LOC_DEGREES + uint32(m2)*dns.LOC_HOURS + uint32(s2*1000)
```
Comment (kevinji) [inline models/t_loc.go:103]: I removed the uint64 cast here because we recast back to uint32 immediately afterwards.
